/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Producto;
import Clases.Usuario;
import Clases.UsuarioSesion;
import Servicios.WsCategoria;
import Servicios.WsOferta;
import Servicios.WsProducto;
import Servicios.WsTienda;
import Vista.modal.modal_adm_productos;
import Vista.modal.modal_productos;
import java.awt.event.ItemEvent;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;

/**
 *
 * @author Sony
 */
public class adm_productos extends javax.swing.JFrame {

    /**
     * Creates new form adm_productos
     */
    private static adm_productos obj = null;
    private static Home first = null;

    public adm_productos() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnl_detalle.setVisible(false);

        Usuario usu = UsuarioSesion.UsuSesion;

        cargarTiendas(usu.getTienda_id());
        cargarCategorias(0);
        cmb_tienda_hide.setVisible(false);
        cbo_categoria_hide.setVisible(false);
    }

    public static adm_productos getObj(Home f) {
        first = f;
        if (obj == null) {
            obj = new adm_productos();
        }
        return obj;
    }

    public void cargarTiendas(Integer tnd_id) {

        WsTienda ws = new WsTienda();
        String retorno = "";
        retorno = ws.WSfn_TraerTienda(tnd_id);

        if (!retorno.equals("<NewDataSet />")) {
            try {
                SAXBuilder builder = new SAXBuilder();

                InputStream stream = new ByteArrayInputStream(retorno.getBytes("UTF-8"));
                Document document = builder.build(stream);

                //Document document = (Document) builder.build(retorno);
                Element rootNode = document.getRootElement();
                java.util.List<Element> list = rootNode.getChildren("Table");

                for (int i = 0; i < list.size(); i++) {

                    Element node = (Element) list.get(i);

                    String id = node.getChildText("TND_ID");
                    String descripcion = node.getChildText("TND_DESCRIPCION");

                    cmb_tienda.addItem(descripcion);
                    cmb_tienda_hide.addItem(id + ':' + descripcion);

                }

            } catch (JDOMException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    public void cargarCategorias(Integer ctg_id) {

        WsCategoria ws = new WsCategoria();
        String retorno = "";
        retorno = ws.WSfn_TraerCategoria(ctg_id);

        if (!retorno.equals("<NewDataSet />")) {
            try {
                SAXBuilder builder = new SAXBuilder();

                InputStream stream = new ByteArrayInputStream(retorno.getBytes("UTF-8"));
                Document document = builder.build(stream);

                //Document document = (Document) builder.build(retorno);
                Element rootNode = document.getRootElement();
                java.util.List<Element> list = rootNode.getChildren("Table");

                for (int i = 0; i < list.size(); i++) {

                    Element node = (Element) list.get(i);

                    String id = node.getChildText("CTG_ID");
                    String descripcion = node.getChildText("CTG_DESCRIPCION");

                    cbo_categoria.addItem(descripcion);
                    cbo_categoria_hide.addItem(id + ':' + descripcion);

                }

            } catch (JDOMException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_busqueda = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmb_tienda = new javax.swing.JComboBox<>();
        cmb_tienda_hide = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        pnl_detalle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_codigo_barra = new javax.swing.JTextField();
        cbo_categoria = new javax.swing.JComboBox<>();
        lbl_codigo = new javax.swing.JLabel();
        cbo_categoria_hide = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_precio_c = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_precio_v = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Administracion de Productos");

        cmb_tienda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tiendaItemStateChanged(evt);
            }
        });

        jLabel8.setText("Tienda");

        javax.swing.GroupLayout pnl_busquedaLayout = new javax.swing.GroupLayout(pnl_busqueda);
        pnl_busqueda.setLayout(pnl_busquedaLayout);
        pnl_busquedaLayout.setHorizontalGroup(
            pnl_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_busquedaLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(pnl_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(pnl_busquedaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(56, 56, 56)
                        .addGroup(pnl_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_tienda_hide, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addComponent(btn_buscar)))
                .addGap(41, 41, 41)
                .addComponent(btn_nuevo)
                .addGap(169, 169, 169))
        );
        pnl_busquedaLayout.setVerticalGroup(
            pnl_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_busquedaLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(pnl_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_busquedaLayout.createSequentialGroup()
                        .addGroup(pnl_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_tienda_hide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_buscar)
                        .addComponent(btn_nuevo)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setText("Codigo");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripcion");

        jLabel4.setText("Codigo barra");

        jLabel5.setText("Categoria");

        cbo_categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_categoriaItemStateChanged(evt);
            }
        });

        lbl_codigo.setText("...");

        jLabel6.setText("Precio compra");

        jLabel7.setText("Precio venta");

        jButton1.setText("Ver");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("administrar imagenes");

        javax.swing.GroupLayout pnl_detalleLayout = new javax.swing.GroupLayout(pnl_detalle);
        pnl_detalle.setLayout(pnl_detalleLayout);
        pnl_detalleLayout.setHorizontalGroup(
            pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detalleLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btn_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_guardar)
                .addGap(45, 45, 45))
            .addGroup(pnl_detalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_detalleLayout.createSequentialGroup()
                        .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_codigo)
                            .addGroup(pnl_detalleLayout.createSequentialGroup()
                                .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nombre)
                                    .addComponent(cbo_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(cbo_categoria_hide, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_detalleLayout.createSequentialGroup()
                                .addComponent(txt_precio_c, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel7)
                                .addGap(40, 40, 40)
                                .addComponent(txt_precio_v, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_detalleLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_detalleLayout.setVerticalGroup(
            pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detalleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_codigo))
                .addGap(29, 29, 29)
                .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbo_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_categoria_hide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_precio_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_precio_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_eliminar))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_detalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed

        limpiar_form();
        pnl_detalle.setVisible(true);
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        limpiar_form();
        Integer tnd_id;

        String item = cmb_tienda_hide.getSelectedItem().toString();
        String[] parts = item.split(":");

        tnd_id = Integer.parseInt(parts[0]);

        modal_adm_productos.getObj(this, tnd_id).setVisible(true);
    }//GEN-LAST:event_btn_buscarActionPerformed

    public void agregar_producto(Producto pr) {

        pnl_detalle.setVisible(true);

        lbl_codigo.setText(pr.getId().toString());
        txt_codigo_barra.setText(pr.getCodBarra());
        txt_nombre.setText(pr.getDescripcion());
        txt_precio_c.setText(pr.getPrecioCompra().toString());
        txt_precio_v.setText(pr.getPrecioVenta().toString());

        Integer categoria = pr.getCategoriaId();

        int size = cbo_categoria_hide.getItemCount();
        for (int i = 0; i < size; i++) {
            String item = cbo_categoria_hide.getItemAt(i);
            String[] parts = item.split(":");
            int id = Integer.parseInt(parts[0]);
            if (id == categoria) {
                cbo_categoria_hide.setSelectedIndex(i);
                cbo_categoria.setSelectedIndex(i);
                i = size;
            }
        }
    }

    public void limpiar_form() {
        lbl_codigo.setText("...");
        txt_codigo_barra.setText("");
        txt_nombre.setText("");
        txt_precio_c.setText("");
        txt_precio_v.setText("");

    }
    private void cbo_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_categoriaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            Integer index = cbo_categoria.getSelectedIndex();
            if (cbo_categoria_hide.getSelectedIndex() > -1) {
                cbo_categoria_hide.setSelectedIndex(index);
            }

            //JOptionPane.showMessageDialog(null, (String) evt.getItem());
        }
    }//GEN-LAST:event_cbo_categoriaItemStateChanged

    private void cmb_tiendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tiendaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            Integer index = cmb_tienda.getSelectedIndex();
            if (cmb_tienda_hide.getSelectedIndex() > -1) {
                limpiar_form();
                cmb_tienda_hide.setSelectedIndex(index);
            }

            //JOptionPane.showMessageDialog(null, (String) evt.getItem());
        }
    }//GEN-LAST:event_cmb_tiendaItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        limpiar_form();
        obj = null;

    }//GEN-LAST:event_formWindowClosing

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        if (validarOferta()) {

            Integer tienda = 0;
            String tipo = "";
            Integer prd_id = 0;
            Integer codigoBarra = 0;
            String nombre = "";
            Integer categoria = 0;
            Integer precioV = 0;
            Integer precioC = 0;

            String[] partsTienda = cmb_tienda_hide.getSelectedItem().toString().split(":");
            tienda = Integer.parseInt(partsTienda[0]);

            String[] partsCategoria = cbo_categoria_hide.getSelectedItem().toString().split(":");
            categoria = Integer.parseInt(partsCategoria[0]);
            codigoBarra = Integer.parseInt(txt_codigo_barra.getText().toString().trim());
            nombre = txt_nombre.getText().toString().trim();
            precioV = Integer.parseInt(txt_precio_v.getText().toString().trim());
            precioC = Integer.parseInt(txt_precio_c.getText().toString().trim());

            WsProducto ws = new WsProducto();
            String retorno;
            if (lbl_codigo.getText().equals("...")) {
                tipo = "do";
                retorno = ws.WSfn_GuardarProducto(tipo, codigoBarra, nombre, precioC, categoria, precioV, tienda, prd_id);
                MensajeGuardar(retorno);
            } else {
                tipo = "set";
                prd_id = Integer.parseInt(lbl_codigo.getText());
                retorno = ws.WSfn_GuardarProducto(tipo, codigoBarra, nombre, precioC, categoria, precioV, tienda, prd_id);
                MensajeActualiza(retorno);

            }

        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (!lbl_codigo.getText().equals("...")) {

            Integer respuesta = JOptionPane.showConfirmDialog(this, "¿Esta Seguro que desea Eliminar?", "Productos", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {

                int id_prd = Integer.parseInt(lbl_codigo.getText().toString());
                WsProducto ws = new WsProducto();
                String retorno;
                retorno = ws.WSfn_EliminarProducto(id_prd);
                JOptionPane.showMessageDialog(this, retorno);
                limpiar_form();

            }

        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    public void MensajeGuardar(String respuesta) {

        String mensaje = "";
        if (!respuesta.equals("")) {
            try {
                Integer.parseInt(respuesta);
                mensaje = "Producto registrado Correctamente";
                limpiar_form();
            } catch (Exception ex) {
                mensaje = "Error WS: " + respuesta;
            }

        } else {
            mensaje = "Error de comunicacion, no se pudo guardar";

        }
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void MensajeActualiza(String respuesta) {

        String mensaje = "";
        if (!respuesta.equals("")) {

            mensaje = respuesta;
            limpiar_form();

        } else {
            mensaje = "Error de comunicacion, no se pudo actualizar";

        }
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public boolean validarOferta() {

        String mensaje = "";
        boolean valida = true;

        if (cmb_tienda.getSelectedIndex() == -1) {
            mensaje = "Seleccione una tienda";
            valida = false;
        }
        if (valida == true & txt_codigo_barra.getText().toString().trim().equals("")) {
            mensaje = "Ingrese Codigo de barra";
            valida = false;
        } else {
            try {
                Integer.parseInt(txt_codigo_barra.getText());
            } catch (Exception ex) {
                mensaje = "Campo Codigo Barra solo numerico";
                valida = false;
            }
        }
        if (valida == true & txt_nombre.getText().toString().trim().equals("")) {
            mensaje = "ingrese descripcion del producto";
            valida = false;
        }
        if (valida == true & cbo_categoria.getSelectedIndex() == -1) {
            mensaje = "Seleccione una categoria";
            valida = false;
        }
        if (valida == true & txt_precio_c.getText().toString().trim().equals("")) {
            mensaje = "ingrese precio de compra";
            valida = false;
        } else {
            try {
                Integer.parseInt(txt_precio_c.getText().replace(".", ""));
            } catch (Exception ex) {
                mensaje = "Campo Precio Compra solo numerico";
                valida = false;
            }
        }
        if (valida == true & txt_precio_v.getText().toString().trim().equals("")) {
            mensaje = "ingrese precio de venta";
            valida = false;
        } else {
            try {
                Integer.parseInt(txt_precio_v.getText().replace(".", ""));
            } catch (Exception ex) {
                mensaje = "Campo Precio venta solo numerico";
                valida = false;
            }
        }

        if (valida == false) {
            JOptionPane.showMessageDialog(this, mensaje);
        }

        return valida;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adm_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adm_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adm_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adm_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adm_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JComboBox<String> cbo_categoria;
    private javax.swing.JComboBox<String> cbo_categoria_hide;
    private javax.swing.JComboBox<String> cmb_tienda;
    private javax.swing.JComboBox<String> cmb_tienda_hide;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JPanel pnl_busqueda;
    private javax.swing.JPanel pnl_detalle;
    private javax.swing.JTextField txt_codigo_barra;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio_c;
    private javax.swing.JTextField txt_precio_v;
    // End of variables declaration//GEN-END:variables

}
